server:
  port: 8082
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: bolina1497
   
  jpa: 
    hibernate: 
      ddl-auto: update
    